create table class(
                      class_id int generated by default as identity,
                      course_id varchar(255),
                      lecturer_id int,
                      room_id int,
                      person_register int,
                      person_max int,
                      opened int,
                      begin varchar(255),
                      end varchar(255),
                      primary key(class_id)
);